version: '3'
services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./site/:/var/www/${PROJECT}/
        networks:
            - diw2daw
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./site/:/var/www/${PROJECT}/
        ports:
            - 8006:8006
        networks:
            - diw2daw

volumes:
    db5_app:

networks:
    diw2daw:
        driver: bridge
        ipam:
            config:
                - subnet: 172.201.0.0/16